baseURL = 'https://gomisr.github.io/trabajo_hugo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme= "relearn"

[params.author]
    name = 'Sören Weber'

  [[params.boxStyle]]
    color = 'gold'
    i18n = ''
    icon = 'rainbow'
    identifier = 'magic'
    title = 'Magic'

  [params.image]
    errorlevel = 'error'

  [params.imageEffects]
    border = true
    lazy = true
    lightbox = true
    shadow = false

  [params.include]
    errorlevel = 'error'

  [params.link]
    errorlevel = 'error'

  [params.openapi]
    errorlevel = 'error'

  [params.social]
    facebook_admin = ''
    twitter = ''

  [[params.themeVariant]]
    auto = []
    identifier = 'relearn-auto'
    name = 'Relearn Light/Dark'

  [[params.themeVariant]]
    identifier = 'relearn-light'

  [[params.themeVariant]]
    identifier = 'relearn-dark'

  [[params.themeVariant]]
    identifier = 'relearn-bright'

  [[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Zen Light/Dark'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

  [[params.themeVariant]]
    auto = ['learn', 'neon']
    identifier = 'retro-auto'
    name = 'Retro Learn/Neon'

  [[params.themeVariant]]
    identifier = 'neon'

  [[params.themeVariant]]
    identifier = 'learn'

  [[params.themeVariant]]
    identifier = 'blue'

  [[params.themeVariant]]
    identifier = 'green'

  [[params.themeVariant]]
    identifier = 'red'